### 练习 2：测试商品接口
### 启动项目后，点击每个请求左边的绿色箭头运行

### 1. 根据 ID 查询商品
# TODO: 写一个 GET 请求，查询 id 为 1 的商品


### 2. 搜索商品（不带参数）
# TODO: 写一个 GET 请求，不带任何查询参数


### 3. 搜索商品（带参数）
# TODO: 写一个 GET 请求，带上 name=手机 和 maxPrice=5000


### 4. 创建商品
# TODO: 写一个 POST 请求，请求体为 JSON，包含 name、price、stock


### 5. 更新商品
# TODO: 写一个 PUT 请求，更新 id 为 1 的商品，请求体为 JSON


### 6. 删除商品
# TODO: 写一个 DELETE 请求，删除 id 为 1 的商品
